.TH "Bishop" 3 "Wed May 31 2017" "Chess" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bishop \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bishop\&.h>\fP
.PP
Inherits \fBPiece\fP\&.
.PP
Inherited by \fBQueen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBishop\fP ()"
.br
.ti -1c
.RI "\fBBishop\fP (string \fBposition\fP)"
.br
.ti -1c
.RI "virtual \fB~Bishop\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetAvailPositions\fP (\fBPiece\fP **all)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file Bishop\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bishop::Bishop ()"

.SS "Bishop::Bishop (string position)\fC [inline]\fP"

.PP
Definition at line 27 of file Bishop\&.h\&.
.SS "Bishop::~Bishop ()\fC [virtual]\fP"

.PP
Definition at line 11 of file Bishop\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "vector<string> Bishop::getAvailPositions (\fBPiece\fP ** all)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPiece\fP\&.
.PP
Reimplemented in \fBQueen\fP\&.
.PP
Definition at line 33 of file Bishop\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess from the source code\&.
