.TH "Colors.h" 3 "Wed May 31 2017" "Chess" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Colors.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRESET\fP   '\\033[0m'"
.br
.ti -1c
.RI "#define \fBBLACK\fP   '\\033[30m'      /* Black */"
.br
.ti -1c
.RI "#define \fBRED\fP   '\\033[31m'      /* Red */"
.br
.ti -1c
.RI "#define \fBGREEN\fP   '\\033[32m'      /* Green */"
.br
.ti -1c
.RI "#define \fBYELLOW\fP   '\\033[33m'      /* Yellow */"
.br
.ti -1c
.RI "#define \fBBLUE\fP   '\\033[34m'      /* Blue */"
.br
.ti -1c
.RI "#define \fBMAGENTA\fP   '\\033[35m'      /* Magenta */"
.br
.ti -1c
.RI "#define \fBCYAN\fP   '\\033[36m'      /* Cyan */"
.br
.ti -1c
.RI "#define \fBWHITE\fP   '\\033[37m'      /* White */"
.br
.ti -1c
.RI "#define \fBBOLDBLACK\fP   '\\033[1m\\033[30m'      /* Bold Black */"
.br
.ti -1c
.RI "#define \fBBOLDRED\fP   '\\033[1m\\033[31m'      /* Bold Red */"
.br
.ti -1c
.RI "#define \fBBOLDGREEN\fP   '\\033[1m\\033[32m'      /* Bold Green */"
.br
.ti -1c
.RI "#define \fBBOLDYELLOW\fP   '\\033[1m\\033[33m'      /* Bold Yellow */"
.br
.ti -1c
.RI "#define \fBBOLDBLUE\fP   '\\033[1m\\033[34m'      /* Bold Blue */"
.br
.ti -1c
.RI "#define \fBBOLDMAGENTA\fP   '\\033[1m\\033[35m'      /* Bold Magenta */"
.br
.ti -1c
.RI "#define \fBBOLDCYAN\fP   '\\033[1m\\033[36m'      /* Bold Cyan */"
.br
.ti -1c
.RI "#define \fBBOLDWHITE\fP   '\\033[1m\\033[37m'      /* Bold White */"
.br
.ti -1c
.RI "#define \fBINVERSE\fP   '\\033[7m'     /* Swap Bacground and Text colors */"
.br
.ti -1c
.RI "#define \fBUNDERLINE\fP   '\\033[4m'     /* Underline Single */"
.br
.ti -1c
.RI "#define \fBBGBLACK\fP   '\\033[40m'      /* BLACK Background */"
.br
.ti -1c
.RI "#define \fBBGRED\fP   '\\033[41m'      /* RED Background */"
.br
.ti -1c
.RI "#define \fBBGGREEN\fP   '\\033[42m'      /* GREEN Background */"
.br
.ti -1c
.RI "#define \fBBGYELLOW\fP   '\\033[43m'      /* YELLOW Background */"
.br
.ti -1c
.RI "#define \fBBGBLUE\fP   '\\033[44m'      /* BLUE Background */"
.br
.ti -1c
.RI "#define \fBBGMAGENTA\fP   '\\033[45m'      /* MAGENTA Background */"
.br
.ti -1c
.RI "#define \fBBGCYAN\fP   '\\033[46m'      /* CYAN Background */"
.br
.ti -1c
.RI "#define \fBBGWHITE\fP   '\\033[47m'      /* WHITE Background */"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BGBLACK   '\\033[40m'      /* BLACK Background */"

.PP
Definition at line 33 of file Colors\&.h\&.
.SS "#define BGBLUE   '\\033[44m'      /* BLUE Background */"

.PP
Definition at line 37 of file Colors\&.h\&.
.SS "#define BGCYAN   '\\033[46m'      /* CYAN Background */"

.PP
Definition at line 39 of file Colors\&.h\&.
.SS "#define BGGREEN   '\\033[42m'      /* GREEN Background */"

.PP
Definition at line 35 of file Colors\&.h\&.
.SS "#define BGMAGENTA   '\\033[45m'      /* MAGENTA Background */"

.PP
Definition at line 38 of file Colors\&.h\&.
.SS "#define BGRED   '\\033[41m'      /* RED Background */"

.PP
Definition at line 34 of file Colors\&.h\&.
.SS "#define BGWHITE   '\\033[47m'      /* WHITE Background */"

.PP
Definition at line 40 of file Colors\&.h\&.
.SS "#define BGYELLOW   '\\033[43m'      /* YELLOW Background */"

.PP
Definition at line 36 of file Colors\&.h\&.
.SS "#define BLACK   '\\033[30m'      /* Black */"

.PP
Definition at line 13 of file Colors\&.h\&.
.SS "#define BLUE   '\\033[34m'      /* Blue */"

.PP
Definition at line 17 of file Colors\&.h\&.
.SS "#define BOLDBLACK   '\\033[1m\\033[30m'      /* Bold Black */"

.PP
Definition at line 21 of file Colors\&.h\&.
.SS "#define BOLDBLUE   '\\033[1m\\033[34m'      /* Bold Blue */"

.PP
Definition at line 25 of file Colors\&.h\&.
.SS "#define BOLDCYAN   '\\033[1m\\033[36m'      /* Bold Cyan */"

.PP
Definition at line 27 of file Colors\&.h\&.
.SS "#define BOLDGREEN   '\\033[1m\\033[32m'      /* Bold Green */"

.PP
Definition at line 23 of file Colors\&.h\&.
.SS "#define BOLDMAGENTA   '\\033[1m\\033[35m'      /* Bold Magenta */"

.PP
Definition at line 26 of file Colors\&.h\&.
.SS "#define BOLDRED   '\\033[1m\\033[31m'      /* Bold Red */"

.PP
Definition at line 22 of file Colors\&.h\&.
.SS "#define BOLDWHITE   '\\033[1m\\033[37m'      /* Bold White */"

.PP
Definition at line 28 of file Colors\&.h\&.
.SS "#define BOLDYELLOW   '\\033[1m\\033[33m'      /* Bold Yellow */"

.PP
Definition at line 24 of file Colors\&.h\&.
.SS "#define CYAN   '\\033[36m'      /* Cyan */"

.PP
Definition at line 19 of file Colors\&.h\&.
.SS "#define GREEN   '\\033[32m'      /* Green */"

.PP
Definition at line 15 of file Colors\&.h\&.
.SS "#define INVERSE   '\\033[7m'     /* Swap Bacground and Text colors */"

.PP
Definition at line 30 of file Colors\&.h\&.
.SS "#define MAGENTA   '\\033[35m'      /* Magenta */"

.PP
Definition at line 18 of file Colors\&.h\&.
.SS "#define RED   '\\033[31m'      /* Red */"

.PP
Definition at line 14 of file Colors\&.h\&.
.SS "#define RESET   '\\033[0m'"

.PP
Definition at line 12 of file Colors\&.h\&.
.SS "#define UNDERLINE   '\\033[4m'     /* Underline Single */"

.PP
Definition at line 31 of file Colors\&.h\&.
.SS "#define WHITE   '\\033[37m'      /* White */"

.PP
Definition at line 20 of file Colors\&.h\&.
.SS "#define YELLOW   '\\033[33m'      /* Yellow */"

.PP
Definition at line 16 of file Colors\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess from the source code\&.
