.TH "Queen.h" 3 "Wed May 31 2017" "Chess" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queen.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Bishop\&.h'\fP
.br
\fC#include 'Rook\&.h'\fP
.br
\fC#include 'Piece\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQueen\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess from the source code\&.
