.TH "Piece.cpp" 3 "Wed May 31 2017" "Chess" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Piece.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Piece\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBinvalid\fP (string p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool invalid (string p)"
Check if a position is invalid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP The position string\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
True if the \fBPiece\fP is out of range of A-H, 0-7\&. 
.RE
.PP

.PP
Definition at line 125 of file Piece\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess from the source code\&.
