.TH "Queen" 3 "Wed May 31 2017" "Chess" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queen \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Queen\&.h>\fP
.PP
Inherits \fBBishop\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueen\fP ()"
.br
.ti -1c
.RI "\fBQueen\fP (string \fBposition\fP)"
.br
.ti -1c
.RI "virtual \fB~Queen\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetAvailPositions\fP (\fBPiece\fP **all)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Inherits the \fBBishop\fP's movements, as well as the \fBRook\fP's movements\&. 
.PP
Definition at line 23 of file Queen\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Queen::Queen ()"

.SS "Queen::Queen (string position)\fC [inline]\fP"

.PP
Definition at line 27 of file Queen\&.h\&.
.SS "Queen::~Queen ()\fC [virtual]\fP"

.PP
Definition at line 11 of file Queen\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "vector<string> Queen::getAvailPositions (\fBPiece\fP ** all)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBBishop\fP\&.
.PP
Definition at line 33 of file Queen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess from the source code\&.
