.TH "Card" 3 "Wed Apr 19 2017" "Blackjack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char \fBgetSuit\fP ()"
.br
.ti -1c
.RI "char \fBgetRank\fP ()"
.br
.ti -1c
.RI "short \fBgetVal\fP ()"
.br
.ti -1c
.RI "string \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBcNumber\fP"
.br
.ti -1c
.RI "short \fBsuit\fP"
.br
.ti -1c
.RI "short \fBrank\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Notice - Saving player banks to binary files was taken out last minute due to time constraints\&. I had many problems that were crashing my entire program\&.
.PP
Everything else should be covered\&. 
.PP
Definition at line 25 of file main\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "char Card::getRank ()\fC [inline]\fP"

.PP
Definition at line 40 of file main\&.cpp\&.
.SS "char Card::getSuit ()\fC [inline]\fP"

.PP
Definition at line 32 of file main\&.cpp\&.
.SS "short Card::getVal ()\fC [inline]\fP"

.PP
Definition at line 46 of file main\&.cpp\&.
.SS "string Card::toString ()\fC [inline]\fP"

.PP
Definition at line 62 of file main\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "short Card::cNumber"
test 
.PP
Definition at line 30 of file main\&.cpp\&.
.SS "short Card::rank"

.PP
Definition at line 30 of file main\&.cpp\&.
.SS "short Card::suit"

.PP
Definition at line 30 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack from the source code\&.
