.TH "Player" 3 "Wed Apr 19 2017" "Blackjack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBcard1\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBcard2\fP"
.br
.ti -1c
.RI "vector< \fBCard\fP > \fBhits\fP"
.br
.ti -1c
.RI "short \fBscore\fP = 0"
.br
.ti -1c
.RI "short \fBbet\fP = 0"
.br
.ti -1c
.RI "short \fBbank\fP = 2500"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file main\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "short Player::bank = 2500"

.PP
Definition at line 75 of file main\&.cpp\&.
.SS "short Player::bet = 0"

.PP
Definition at line 75 of file main\&.cpp\&.
.SS "\fBCard\fP Player::card1"

.PP
Definition at line 73 of file main\&.cpp\&.
.SS "\fBCard\fP Player::card2"

.PP
Definition at line 73 of file main\&.cpp\&.
.SS "vector<\fBCard\fP> Player::hits"

.PP
Definition at line 74 of file main\&.cpp\&.
.SS "short Player::score = 0"

.PP
Definition at line 75 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Blackjack from the source code\&.
